spring:
  datasource:    url: jdbc:mysql://localhost:3306/chbw_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: chbwSystem
server:
  port: 8080

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.server.chbw.entity
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
  
